version: '3'
services:
    app:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: student_exam_app
        volumes:
            - .:/app
        ports:
            - "80:80"
        tty: true
        extra_hosts:
            - "host.docker.internal:host-gateway"
    pgsql:
        image: postgres:latest
        container_name: db_student_exam
        ports:
            - "5432:5432"
        volumes:
            - postgres-data:/var/lib/postgresql/data
        environment:
            POSTGRES_PASSWORD: ${DB_PASSWORD}
            POSTGRES_USER: ${DB_USERNAME}
            POSTGRES_DB: ${DB_DATABASE}
    redis:
        image: redis:latest
        container_name: cache_student_exam
        volumes:
            - redis-data:/data
        ports:
            - "6379:6379"

volumes:
    postgres-data:
    redis-data:
